---
id: Stream
name: Stream
full: PHP streams library
description: >-
  A library that provide an object-oriented interface to assist in creating and
  storing PHP stream resources, and to provide utility methods to access and
  manipulate the stream contents.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Stream
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha5
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/exception: ^3
  optional:
    composer:
      horde/stream_wrapper: ^3
      horde/test: ^3
      horde/util: ^3
